### ISSUE TITLE
Thoughts on moving to react?

### ISSUE THREAD

**Issue by tknickman** [Irev-Dev/MRI-Volume-Slice#36]
This is simple application that is really useful, would you be open to moving this over the react? It could help with increasing contributions + new feature development (especially if you're considering using a GraphQL backend) as it's much easier to develop with and has a huge community. 

I would be happy to take this on, but it would be a large shift so I wanted to see what you thought! No issue either way 😄- just a suggestion!

**Comment by Irev-Dev** [comment]
@tknickman Wow thanks for the offer.

I'm really not sure, React is one of those things that I've been meaning to learn but haven't yet. So I'm interested but worried about maintaining the project without that knowledge, hard to enforce best practices when I don't even know the tech ( thought it might be the push I need to actually learn it ).

I've also thinking about writing tests for this project, and it would be a shame to write tests just to have to redo them all because I decide later to move to react (not sure how much would be involved to porting the tests over).

On the other hand, there is a something nice about it being done all in raw JS, so 🤷‍♀️ I danno.

**Comment by tknickman** [comment]
Totally agree 😄. I think you should leave it as is then, maintaining a project in something new is no fun! Thanks for the response 👍

**Comment by Irev-Dev** [comment]
Cool, Thanks again.
